# Generated by Django 5.0.6 on 2025-05-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('sname', models.CharField(max_length=20)),
                ('subjects', models.CharField(max_length=20)),
                ('percentage', models.FloatField()),
            ],
        ),
    ]
