# Generated by Django 5.0.6 on 2025-05-12 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('college_name', models.CharField(max_length=20)),
                ('subjects', models.CharField(max_length=30)),
                ('course', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('mobilenumber', models.IntegerField()),
            ],
        ),
    ]
